idf_component_register(SRCS "main.c"
                            "app/app_core.c"
                            "app/app_cv.c"
                            "bsp/bsp_os.c"
                            "bsp/bsp_storage.c"
                            "bsp/bsp_tcp.c"
                            "bsp/bsp_uart.c"
                            "bsp/bsp_wifi.c"
                            "bsp/bsp_led.c"
                            "bsp/bsp_web.c"
                       INCLUDE_DIRS "." 
                                    "app" 
                                    "bsp"
                       REQUIRES nvs_flash esp_wifi esp_netif lwip esp_driver_uart esp_driver_gpio led_strip esp_http_server mbedtls)